-- ============================================================================
-- Banca Pro — supabase.sql
-- Histórico cumulativo de comandos SQL usados para criar/alterar o banco.
-- ============================================================================
-- Este arquivo é entregue junto com os demais arquivos do projeto
-- (index.html, worker.js, wiki.html, changelog.html, CHANGELOG.md,
-- wrangler.jsonc) a cada atualização que envolver mudança no banco.
--
-- MARCO INICIAL (29/07/2026 — v1.17.0): o bloco "ESTADO ATUAL" abaixo é uma
-- reconstrução fiel do banco tal como ele existe HOJE, obtida consultando
-- diretamente o Supabase (information_schema, pg_policies, pg_proc) — não é
-- um histórico retroativo de cada comando que já foi rodado desde o início
-- do projeto (esses comandos originais não foram registrados em nenhum
-- lugar até agora). A partir desta data, toda mudança nova entra como uma
-- entrada no HISTÓRICO DE MUDANÇAS, no final do arquivo, com data.
--
-- Duas ressalvas sobre a reconstrução abaixo:
--   1) As FOREIGN KEY em "user_id" referenciam auth.users(id) — isso é o
--      padrão do Supabase e bate com o uso no app, mas a consulta ao
--      information_schema não teve permissão de confirmar a tabela de
--      destino (schema auth). Considere confirmado por convenção, não por
--      leitura direta do catálogo.
--   2) Constraints, policies e afins que porventura existam mas não tenham
--      aparecido nas consultas de auditoria (ex.: índices adicionais sem
--      constraint associada) não estão neste arquivo.
-- ============================================================================


-- ============================================================================
-- ESTADO ATUAL — TABELAS (reconstruído em 29/07/2026)
-- ============================================================================

-- ---- apostas ----
create table public.apostas (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null default auth.uid(),                 -- references auth.users(id), não confirmado por leitura direta (ver ressalva 1)
  identificador text not null,
  data_hora timestamp without time zone not null,
  casa text,
  tipster text,
  tipo text,
  status text not null default 'Aberto',
  stake numeric not null default 0,
  odd_total numeric not null default 0,
  recebido numeric not null default 0,
  lucro numeric not null default 0,
  unidades numeric not null default 0,
  roi numeric not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  bonus numeric not null default 0,
  observacao text,
  cash_out_valor numeric,
  constraint apostas_user_identificador_unique unique (user_id, identificador)
);

-- ---- eventos ----
create table public.eventos (
  id uuid not null default gen_random_uuid() primary key,
  aposta_id uuid not null references public.apostas(id),
  user_id uuid not null default auth.uid(),                 -- references auth.users(id), ver ressalva 1
  numero integer not null default 1,
  esporte text,
  liga text,
  evento text,
  mercado text,
  selecao text,
  odd numeric not null default 0
);

-- ---- opcoes ----
create table public.opcoes (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null default auth.uid(),                 -- references auth.users(id), ver ressalva 1
  campo text not null,
  valor text not null
);

-- ---- transacoes ----
create table public.transacoes (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null default auth.uid(),                 -- references auth.users(id), ver ressalva 1
  casa text not null,
  tipo text not null,
  valor numeric not null,
  data timestamp without time zone not null,
  observacao text,
  created_at timestamp with time zone not null default now()
);

-- ---- correcoes_ia (criada na v1.13.0 — Correções Aprendidas) ----
create table public.correcoes_ia (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),                 -- references auth.users(id), ver ressalva 1
  campo text not null,
  esporte text not null,
  valor_errado text not null,
  valor_correto text not null,
  contexto text,
  criado_em timestamp with time zone not null default now()
);

-- ---- profiles ----
-- Populada automaticamente pelo gatilho on_auth_user_created (ver abaixo)
-- a cada novo cadastro em auth.users — não é inserida manualmente pelo app.
create table public.profiles (
  id uuid not null primary key references auth.users(id),
  is_admin boolean not null default false,
  created_at timestamp with time zone not null default now(),
  ai_enabled boolean not null default false,
  ai_calls_count integer not null default 0,
  ai_calls_bilhete integer not null default 0,
  ai_calls_estatisticas integer not null default 0,
  ai_calls_liga integer not null default 0
);


-- ============================================================================
-- ESTADO ATUAL — ROW LEVEL SECURITY (RLS)
-- ============================================================================
-- Todas as tabelas com dado do usuário têm RLS ativado, restringindo cada
-- linha ao próprio dono (auth.uid() = user_id). "profiles" é a exceção: só
-- tem política de leitura (SELECT) da própria linha — updates em profiles
-- acontecem só via as funções SECURITY DEFINER abaixo, que ignoram RLS de
-- propósito.

alter table public.apostas enable row level security;
alter table public.eventos enable row level security;
alter table public.opcoes enable row level security;
alter table public.transacoes enable row level security;
alter table public.correcoes_ia enable row level security;
alter table public.profiles enable row level security;

create policy "apostas: somente o proprio usuario"
  on public.apostas for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "eventos: somente o proprio usuario"
  on public.eventos for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "opcoes: somente o proprio usuario"
  on public.opcoes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "transacoes: somente o proprio usuario"
  on public.transacoes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Usuarios gerenciam suas proprias correcoes"
  on public.correcoes_ia for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "usuarios veem o proprio perfil"
  on public.profiles for select
  using (auth.uid() = id);


-- ============================================================================
-- ESTADO ATUAL — FUNÇÕES
-- ============================================================================

-- Cria a linha em profiles automaticamente quando um novo usuário se
-- cadastra em auth.users. SECURITY DEFINER: precisa ignorar RLS de profiles
-- para conseguir inserir a primeira linha do usuário recém-criado.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $function$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$function$;

-- Mantém updated_at sempre atual em apostas. SECURITY INVOKER (padrão):
-- roda com a permissão de quem chamou, respeitando o RLS normalmente —
-- só toca na própria linha que o usuário já tem permissão de UPDATE.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $function$
begin
    new.updated_at = now();
    return new;
end;
$function$;

-- Contadores de uso de IA, um por funcionalidade + um total geral.
-- Todas SECURITY DEFINER: precisam ignorar RLS de profiles para gravar o
-- contador do usuário sem exigir política de UPDATE liberada para ele.
create or replace function public.increment_ai_calls_count()
returns void
language sql
security definer
as $function$
  update public.profiles
  set ai_calls_count = ai_calls_count + 1
  where id = auth.uid();
$function$;

create or replace function public.increment_ai_calls_bilhete()
returns void
language sql
security definer
as $function$
  update public.profiles
  set ai_calls_bilhete = ai_calls_bilhete + 1,
      ai_calls_count = ai_calls_count + 1
  where id = auth.uid();
$function$;

create or replace function public.increment_ai_calls_estatisticas()
returns void
language sql
security definer
as $function$
  update public.profiles
  set ai_calls_estatisticas = ai_calls_estatisticas + 1,
      ai_calls_count = ai_calls_count + 1
  where id = auth.uid();
$function$;

create or replace function public.increment_ai_calls_liga()
returns void
language sql
security definer
as $function$
  update public.profiles
  set ai_calls_liga = ai_calls_liga + 1,
      ai_calls_count = ai_calls_count + 1
  where id = auth.uid();
$function$;


-- ============================================================================
-- ESTADO ATUAL — GATILHOS (TRIGGERS)
-- ============================================================================

-- Dispara em auth.users (schema do próprio Supabase Auth), não em public.
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create trigger apostas_set_updated_at
  before update on public.apostas
  for each row execute function public.set_updated_at();


-- ============================================================================
-- HISTÓRICO DE MUDANÇAS
-- ============================================================================
-- A partir daqui, cada entrega que envolver mudança no banco ganha um bloco
-- novo aqui, com data, o comando exato rodado e o motivo — no mesmo padrão
-- do CHANGELOG.md do app.

-- (nenhuma mudança registrada ainda após o marco inicial de 29/07/2026)
